version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 10
