language: rust

arch:
  - amd64
  - arm64

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libssl-dev

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
